fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

dahsboard:
    path:     /
    defaults: { _controller: AdminBundle:Dashboard:index }

posts:
    path:     /posts
    defaults:
        _controller: AdminBundle:Post:index
        isPage: false
        orderBy: username
        orderDesc: false

post_add:
    path:     /post/add
    defaults:
        _controller: AdminBundle:Post:addOrEdit
        isPage: false
    methods:  [GET, POST]

post_edit:
    path:     /post/{postId}
    defaults: { _controller: AdminBundle:Post:addOrEdit }
    methods:  [GET, POST]
    requirements:
        postId: ^[0-9A-F]{8}-[0-9A-F]{4}-[1][0-9A-F]{3}-[89AB][0-9A-F]{3}-[0-9A-F]{12}$

post_delete:
    path:     /post/{postId}/delete
    defaults: { _controller: AdminBundle:Post:delete }
    methods:  [GET, POST]
    requirements:
        postId: ^[0-9A-F]{8}-[0-9A-F]{4}-[1][0-9A-F]{3}-[89AB][0-9A-F]{3}-[0-9A-F]{12}$

users:
    path:     /users
    defaults:
        _controller: AdminBundle:User:index
        isPage: false
        orderBy: username
        orderDesc: false
    methods:  [GET, POST]

user_add:
    path:     /user/add
    defaults: { _controller: AdminBundle:User:addOrEdit, userId: null }
    methods:  [GET, POST]

user_edit:
    path:     /user/{userId}
    defaults: { _controller: AdminBundle:User:addOrEdit }
    methods:  [GET, POST, PUT]
    requirements:
        userId: ^[0-9A-F]{8}-[0-9A-F]{4}-[1][0-9A-F]{3}-[89AB][0-9A-F]{3}-[0-9A-F]{12}$

user_delete:
    path:     /user/{userId}/delete
    defaults: { _controller: AdminBundle:User:delete }
    methods:  [GET, POST, DELETE]
    requirements:
        userId: ^[0-9A-F]{8}-[0-9A-F]{4}-[1][0-9A-F]{3}-[89AB][0-9A-F]{3}-[0-9A-F]{12}$
